source "http://rubygems.org"

gem 'selenium-webdriver'
gem 'rspec', '2.14.0'
gem 'appium_lib', '8.0.0'
gem 'activesupport', '4.0.0'
gem 'cucumber', '3.1.0', require: false
gem 'rake', '13.0.1'
gem 'rake', '13.0.1'
gem 'macaddr', '1.6.1'
gem 'selenium-webdriver'